Weather - App
karthykarthick/weather-app pull request #1
Opened 2021-02-16 21:14 UTC by karthykarthick

A weather app built by Js using The concepts that i understand  It fetches your current location and display the weather
- You can Search your favourite City

2021-02-16 21:48 UTC, blackpintz requested changes
# Status: Changes Required 🛑

### Hello team 👋,

**Great job implementing the requested changes 👏.**

### Highlights

- **Your linter checks are properly configured.**
- **App design looks good.**

### Mandatory requirements.

-  **There should be a toggle control to determine if the result will be shown in Celsius or Fahrenheit ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/javascript/weather_app/search_requirement.png) from [Odin](https://www.theodinproject.com/courses/javascript/lessons/weather-app)).**

- **Remove unnecessary folders like the `component` folder.**

### Optional

- **Provide more details, in your README file on how to use your application. For Example, what HTML file should the user preview, the one in `dist` or `src` folder..**

### Happy coding 🥂.

**You can reach  me on slack (Rose Wanjohi).**

2021-02-16 21:48 UTC, blackpintz commented on src/index.js
> +    console.log(weatherData);
Remove this `console.log`.

2021-02-16 23:19 UTC, NtwaliHeritier requested changes
### **STATUS: CHANGES REQUESTED🛑🛑**

Hello @karthykarthick 
Great implementation of the project. I love how easy you made it look.
However let's make some changes to make the project more professional.

[REQUIRED] When you enter a city, the background should change
[REQUIRED] Remove the empty index.js file in components folder 
[REQUIRED] in src/index.js, on line 20, 24, use ES6. Instead of var use let or const.

Make the requested changes and submit for another review👍

2021-02-17 08:14 UTC, karthykarthick commented
When you enter a city, the background should change it is not specified in requirements

2021-02-17 10:41 UTC, Temmarie approved these changes
## Status: Approved :heavy_check_mark:

### Hi @karthykarthick  ! :wave:

#### I really liked the simplicity of your project! Thank you for making all of the required changes, your project is approved :clap: :clap: :clap: :tada:

#### You may merge, good luck with your next projects! :rocket:
#### Happy Coding! :+1:
__Grace Tamara Ekunola __
[GitHub](https://github.com/temmarie) | [LinkedIn](https://www.linkedin.com/in/ekunola-grace/) | [Twitter](https://twitter.com/TemmarieW)

2021-02-17 10:53 UTC, merged